# Software

You will need to have all of the following free software downloaded and in working order on your laptop.

::: {.callout-important}
## Prior to first lecture

You must have the following on your laptops prior to the first lecture.
:::

- Latest version of [RStudio Desktop IDE](https://posit.co/downloads/){target="_blank"}
- Compatible version of [R software environment](https://ftp.osuosl.org/pub/cran/){target="_blank"}
- [Quarto](https://quarto.org/docs/get-started/){target="_blank"} publishing system (for documents with integrated code).
- You must have a functional PDF Engine to render Quarto (`.qmd`) documents into PDF. See this section on [PDF Engines](https://quarto.org/docs/output-formats/pdf-engine.html){target="_blank"}, and be sure to test whether you can render an example `.qmd` file into a PDF. 

::: {.callout-important}
## Prior to Bayesian inference

You must have the following on your laptops prior to the sections on Bayesian inference.
:::

- Stan programming language, via the [rstan](https://mc-stan.org/users/interfaces/rstan.html){target="_blank"} package for R.
- We will potentially use the R package `rstanarm`, but this is a straightforward package to download using the `install.packages()` function.


